### ISSUE TITLE
exporting a subset of the data

### ISSUE THREAD

**Issue by gregbunce** [agrc/open-sgid#10]
From: Phoebe
This may be user error, but if you need to export out a portion of a layer (ex. I am trying to export the 5000’ contour for Salt Lake County to denote the Provo shoreline) the following error pops up:
Error exporting data.
Each grid size must be at least three times larger than the preceding grid size.
The table was not found [Export_Output]

**Comment by steveoh** [comment]
This might be something that requires esri support. Do you think Phoebe would be open to leading that or should we try to reproduce and take it on?
