### ISSUE TITLE
Suggest use of Layer Files

### ISSUE THREAD

**Issue by rkelson** [agrc/open-sgid#18]
#9 
I suggest we add something like the following to _The workaround_ section:
"To avoid having to do this in the future you can utilize `Save As Layer File` in Esri software to store this unique identifier field and and the layers calculated extent."

**Comment by steveoh** [comment]
This would only be for arcmap correct? As pro does not have this "issue"

**Comment by rkelson** [comment]
Yeah it looks like only ArcMap has this unique identifier issue however a layer file in Pro does not make you calculate the extent every time you add the layer.

**Comment by steveoh** [comment]
done.
