### ISSUE TITLE
Duplicate data in location.address_points

### ISSUE THREAD

**Issue by brycelund** [agrc/open-sgid#27]
There are thousands of addresses duplicated several times in the database.

Running the following shows the same address listed 20 times
`SELECT * FROM location.address_points WHERE fulladd LIKE '19 COUGAR LN'`

**Comment by steveoh** [comment]
@ZachBeck or @eneemann is this expected? 

The possible reasons...

- sub addresses e.g. apartments
- sweeper is not removing duplicates 
- or forklift is all fouled up

**Comment by eneemann** [comment]
I believe this is a problem in the data provided to us by the county stewards.  Typically in this situation, the points are missing subaddress information that should be included.  For the '19 Cougar Ln' example in San Juan county, these points are all located on the same cluster of buildings, but are missing unit information.

Sweeper only removes full duplicates (both attributes and geometry are duplicated), however, these points are placed in different locations, so they aren't full duplicates.  We have no way of knowing which point is "correct", so we leave them as-is.  I believe this is an ongoing area where Zach provides feedback to the counties when he encounters the issue.  For San Juan, we haven't received a data update from them in a while and are working with them to update/improve their data.

**Comment by steveoh** [comment]
Should the issue be closed or do we have further work to do?
